Isce3 rtc
ASFOpenSARlab/opensarlab-envs pull request #28
Opened 2023-04-05 17:16 UTC by Alex-Lewandowski

Add isce3_rtc env that installs OPERA's s1-reader and rtc packages

2023-04-05 20:50 UTC, ruikawahara approved these changes
Reviewed changes for ISCE3 - confirmed the addition of `.yml` file, helper script, and proper adjustment for env creation notebook.

2023-04-05 21:54 UTC, dgpalmieri requested changes
Need to make a couple changes to the `isce3_rtc.sh` script that I made in the [isce3_rtc binder](https://github.com/ASFOpenSARlab/opensarlab-notebooks/blob/binder_isce3_rtc/binder/postBuild)

2023-04-05 21:54 UTC, dgpalmieri commented on Scripts/isce3_rtc.sh
We should merge in the changes to this script from the binder branch, I fixed a couple bugs there that are still present here.

2023-05-11 01:02 UTC, dgpalmieri commented
These changes from https://github.com/OPERA-Cal-Val/calval-RTC/pull/6

2023-05-12 03:24 UTC, dgpalmieri commented
I've verified that the env does build and can successfully run the isce3 notebook

2023-05-15 22:16 UTC, Alex-Lewandowski commented
Add isce3_rtc env

2023-05-15 22:17 UTC, merged